### ISSUE TITLE
Activity with "_" in its name

### ISSUE THREAD

**Issue by Irevun** [eduardopenedo/google_classroom_downloader#82]
Hi, first of all thanks for your script and second of all I have a small problem: there is an activity with "_" and everytime the script reaches that files it stops giving an error. I would like to know if there is any way to skip a class or an activity or change the name of an specific activity before downloading.

Thanks.

**Comment by Irevun** [comment]
Thanks you for answering that fast. It simply stops.
[Here is the error](https://i.imgur.com/y2nhPwv.png)

**Comment by eduardopenedo** [comment]
The log screenshot was very useful. Try download now using the beta realease 

Beta link 👇
https://github.com/eduardopenedo/google_classroom_downloader/tree/beta

**Comment by Irevun** [comment]
Okay thanks again for your help. The first time it reached that activity using the beta it crashed. Then everytime I try the script again it seems to give me [the same error ](https://i.imgur.com/NHuHIiz.png)

**Comment by eduardopenedo** [comment]
Try again please, sir

**Comment by Irevun** [comment]
Thanks for your work! Now it downloads the "" activities but I get a [new error](https://i.imgur.com/9ungRsO.png).

**Comment by eduardopenedo** [comment]
check now please

**Comment by Irevun** [comment]
Sorry taking this long had to leave for few hours. This is [what I get now](https://i.imgur.com/pMkAXXu.png)

**Comment by eduardopenedo** [comment]
No problem. 
Beta v4 released

**Comment by Irevun** [comment]
It is now working flawlessly thanks for your work but don't close the issue yet I'm still downloading I'll let you know when it has finished. I don't think I can thank you enough.

**Comment by Irevun** [comment]
Sorry for bothering you again... I got a [new error](https://i.imgur.com/8o942Sv.png) near the end of the download

**Comment by eduardopenedo** [comment]
No problem, you re helping me to improve the script.
Beta v5 released

**Comment by Irevun** [comment]
Ok, I don't know if there is anything left to download but [this](https://i.imgur.com/XXpchdE.png) was the last thing I got.

**Comment by Irevun** [comment]
I've just checked and everything is downloaded. Thank you for your work as I told you before I can't thank you enough.
However it still gives [this](https://i.imgur.com/7WPoMlN.png) when ending so I don't know if it is intended to be like this or is an error. I don't close the issue if you want me to test anything if there isn't anything left let me know. Thanks.

**Comment by eduardopenedo** [comment]
I really do not know why the title of this file was not given, I just jumped to avoid the crash of the script. Fixed added to remove special characters from gdrive (images that are not downloaded)

**Comment by Irevun** [comment]
[This happened ](https://i.imgur.com/m7EroFk.png). Let me know if you want me to try again.

**Comment by eduardopenedo** [comment]
Try again please

**Comment by Irevun** [comment]
Sorry for taking so long was a bit busy. Everything worked as expected [:)](https://i.imgur.com/5G7MyiI.png). Now everthing is downloaded. Thanks for your awesome work. Let me know if I should close the issue or if you want me to test anything more.

**Comment by eduardopenedo** [comment]
You're welcome friend. Hope you do well in your studies.
As everything worked, I will close the issue.
